
#ifndef KEYBOARD_ANORAK_91TKL_BACKLIGHT_ANIMATIONS_CONWAY_H_
#define KEYBOARD_ANORAK_91TKL_BACKLIGHT_ANIMATIONS_CONWAY_H_

void set_animation_conway(void);

#endif /* KEYBOARD_ANORAK_91TKL_BACKLIGHT_ANIMATIONS_CONWAY_H_ */
